export class PrivacyPage {
  private element: HTMLElement;

  constructor() {
    this.element = this.createElement();
  }

  private createElement(): HTMLElement {
    const page = document.createElement("div");
    page.className = "page-container privacy-page";
    page.innerHTML = `
      <div class="page-content">
        <header class="page-header">
          <button class="back-button" id="backToMain">
            <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
              <path d="M19 12H5"></path>
              <path d="M12 19l-7-7 7-7"></path>
            </svg>
            Back to File Hasher
          </button>
        </header>

        <main class="page-main">
          <div class="hero-section">
            <div class="hero-icon">
              <svg width="64" height="64" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5">
                <path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10z"></path>
              </svg>
            </div>
            <h1>Privacy Policy</h1>
            <p class="hero-subtitle">Your privacy is our priority</p>
            <p class="last-updated">Last updated: January 2025</p>
          </div>

          <div class="content-sections">
            <section class="content-section">
              <h2>Our Commitment to Privacy</h2>
              <p>
                File Hasher is designed with privacy as a fundamental principle. This privacy policy 
                explains how we handle your data when you use our hash generation tool. The short version: 
                <strong>we don't collect, store, or transmit any of your personal data or files</strong>.
              </p>
            </section>

            <section class="content-section">
              <h2>What Data We Don't Collect</h2>
              <div class="privacy-list">
                <div class="privacy-item">
                  <div class="privacy-icon no-collect">
                    <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
                      <circle cx="12" cy="12" r="10"></circle>
                      <line x1="15" y1="9" x2="9" y2="15"></line>
                      <line x1="9" y1="9" x2="15" y2="15"></line>
                    </svg>
                  </div>
                  <div>
                    <h4>Your Files</h4>
                    <p>Files you upload are processed entirely in your browser and never sent to our servers.</p>
                  </div>
                </div>
                <div class="privacy-item">
                  <div class="privacy-icon no-collect">
                    <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
                      <circle cx="12" cy="12" r="10"></circle>
                      <line x1="15" y1="9" x2="9" y2="15"></line>
                      <line x1="9" y1="9" x2="15" y2="15"></line>
                    </svg>
                  </div>
                  <div>
                    <h4>Text Input</h4>
                    <p>Any text you enter for hashing remains on your device and is not transmitted anywhere.</p>
                  </div>
                </div>
                <div class="privacy-item">
                  <div class="privacy-icon no-collect">
                    <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
                      <circle cx="12" cy="12" r="10"></circle>
                      <line x1="15" y1="9" x2="9" y2="15"></line>
                      <line x1="9" y1="9" x2="15" y2="15"></line>
                    </svg>
                  </div>
                  <div>
                    <h4>Generated Hashes</h4>
                    <p>The hash values generated by the tool are not stored or logged by us.</p>
                  </div>
                </div>
                <div class="privacy-item">
                  <div class="privacy-icon no-collect">
                    <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
                      <circle cx="12" cy="12" r="10"></circle>
                      <line x1="15" y1="9" x2="9" y2="15"></line>
                      <line x1="9" y1="9" x2="15" y2="15"></line>
                    </svg>
                  </div>
                  <div>
                    <h4>Personal Information</h4>
                    <p>We don't collect names, email addresses, IP addresses, or any identifying information.</p>
                  </div>
                </div>
              </div>
            </section>

            <section class="content-section">
              <h2>Local Storage</h2>
              <p>
                File Hasher uses your browser's local storage only to remember your theme preference 
                (light, dark, or auto mode). This information:
              </p>
              <ul>
                <li>Stays on your device and is never transmitted to us</li>
                <li>Can be cleared by clearing your browser's local storage</li>
                <li>Is not linked to any personal information</li>
                <li>Is used solely to improve your user experience</li>
              </ul>
            </section>

            <section class="content-section">
              <h2>How File Hasher Works</h2>
              <div class="how-it-works">
                <div class="step">
                  <div class="step-number">1</div>
                  <div class="step-content">
                    <h4>You Input Data</h4>
                    <p>You enter text or select a file on your device.</p>
                  </div>
                </div>
                <div class="step">
                  <div class="step-number">2</div>
                  <div class="step-content">
                    <h4>Local Processing</h4>
                    <p>Your browser's JavaScript engine processes the data using cryptographic algorithms.</p>
                  </div>
                </div>
                <div class="step">
                  <div class="step-number">3</div>
                  <div class="step-content">
                    <h4>Hash Generation</h4>
                    <p>The hash is computed and displayed to you instantly.</p>
                  </div>
                </div>
                <div class="step">
                  <div class="step-number">4</div>
                  <div class="step-content">
                    <h4>No Transmission</h4>
                    <p>Nothing leaves your device. All processing happens locally.</p>
                  </div>
                </div>
              </div>
            </section>

            <section class="content-section">
              <h2>Third-Party Services</h2>
              <p>
                File Hasher is a static web application that doesn't integrate with third-party analytics, 
                tracking, or advertising services. The only external resources loaded are:
              </p>
              <ul>
                <li><strong>Google Fonts:</strong> For typography (Inter and JetBrains Mono fonts)</li>
                <li><strong>Hosting Provider:</strong> The application files are served by our hosting provider</li>
              </ul>
              <p>
                These services may have their own privacy policies, but they don't have access to the 
                data you process with File Hasher.
              </p>
            </section>

            <section class="content-section">
              <h2>Open Source Transparency</h2>
              <p>
                File Hasher is open source, meaning you can review the entire codebase to verify our 
                privacy claims. The source code is available on 
                <a href="https://github.com/Elcapitanoe/File-Hasher" target="_blank" rel="noopener noreferrer" class="privacy-link">GitHub</a>, 
                where you can:
              </p>
              <ul>
                <li>Examine how data is processed</li>
                <li>Verify that no network requests are made with your data</li>
                <li>Contribute improvements or report issues</li>
                <li>Run your own instance if desired</li>
              </ul>
            </section>

            <section class="content-section">
              <h2>Data Security</h2>
              <p>
                Since all processing happens locally in your browser, the security of your data depends on:
              </p>
              <ul>
                <li><strong>Your Device:</strong> Keep your device and browser updated</li>
                <li><strong>HTTPS:</strong> We serve File Hasher over HTTPS to prevent tampering</li>
                <li><strong>Browser Security:</strong> Modern browsers provide sandboxing and security features</li>
              </ul>
            </section>

            <section class="content-section">
              <h2>Changes to This Policy</h2>
              <p>
                If we make changes to this privacy policy, we will update the "Last updated" date at the 
                top of this page. Since we don't collect contact information, we can't notify you directly 
                of changes. We recommend checking this page periodically if you're a regular user.
              </p>
            </section>

            <section class="content-section">
              <h2>Contact</h2>
              <p>
                If you have questions about this privacy policy or File Hasher in general, you can:
              </p>
              <ul>
                <li>Open an issue on our <a href="https://github.com/Elcapitanoe/File-Hasher" target="_blank" rel="noopener noreferrer" class="privacy-link">GitHub repository</a></li>
                <li>Contact the developer through GitHub</li>
              </ul>
              <p>
                We're committed to maintaining your privacy and will be happy to address any concerns.
              </p>
            </section>
          </div>
        </main>
      </div>
    `;

    this.setupEventListeners(page);
    return page;
  }

  private setupEventListeners(page: HTMLElement): void {
    const backButton = page.querySelector("#backToMain") as HTMLButtonElement;
    backButton.addEventListener("click", () => {
      this.hide();
    });
  }

  show(): void {
    document.body.appendChild(this.element);
    document.body.style.overflow = "hidden";
  }

  hide(): void {
    if (this.element.parentNode) {
      this.element.parentNode.removeChild(this.element);
    }
    document.body.style.overflow = "";
  }

  getElement(): HTMLElement {
    return this.element;
  }
}
